media:
  templates:
    footer_logo: "new/templates/footer-logo.webp"
  posters:
    upcoming_shows:
      - image_path: "new/posters/Globull.webp"
        web_url: "https://www.instagram.com/necrom_dp"
      - image_path: "new/posters/Nouveau_Monde.webp"
        web_url: "https://www.instagram.com/remi.castella"
    past_shows:
      - image_path: "new/posters/Francos.webp"
      - image_path: "new/posters/Rockies.webp"
      - image_path: "new/posters/Qwertz.webp"
      - image_path: "new/posters/Abyss.webp"
      - image_path: "new/posters/MoB.webp"
  videos:
    - web_url: "https://www.youtube.com/embed/iQOOQ7KFmdE?si=MztkAcw3KF377-3T"
    - web_url: "https://www.youtube.com/embed/IOUMo9eb5gw?si=nfyRtDWbEBnBclSi"
  pictures:
    - image_path: "new/pictures/Abyss-1.webp"
    - image_path: "new/pictures/Abyss-2.webp"
    - image_path: "new/pictures/Bad_Bonn-1.webp"
    - image_path: "new/pictures/Cabane-1.webp"
    - image_path: "new/pictures/Cabane-2.webp"
    - image_path: "new/pictures/First_shooting-1.webp"
    - image_path: "new/pictures/First_shooting-2.webp"
    - image_path: "new/pictures/Francos_2023-1.webp"
    - image_path: "new/pictures/MoB-1.webp"
    - image_path: "new/pictures/MoB-2.webp"
    - image_path: "new/pictures/MoB-3.webp"
    - image_path: "new/pictures/Ruined.webp"
    - image_path: "new/pictures/Globull-1.webp"
  home:
    logo: "new/home/logo.webp"
    background: "new/home/background.webp"
  about:
    logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/logo.webp"
    background: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/background.webp"
band_members:
  - name: "Diogo Pombeiro"
    web_url: "https://www.instagram.com/necrom_dp"
    image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Diogo.webp"
    role: "guitar"
  - name: "Antoine Borcard"
    web_url: "https://www.instagram.com/antbor.s"
    image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Antoine.webp"
    role: "bass"
  - name: "Samuel Bielmann"
    web_url: "https://www.instagram.com/sam_blmn"
    image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Samuel.webp"
    role: "vocals"
  - name: "Simone Dal Molin"
    web_url: "https://www.instagram.com/simd.al08"
    image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Simone.webp"
    role: "drums"
  - name: "Rémi Castella"
    web_url: "https://www.instagram.com/remi.castella"
    image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Rémi.webp"
    role: "guitar"
