media:
  templates:
    footer_logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/templates/footer-logo.webp"
  posters:
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Manoir_Pub_2025"
      web_url: "https://manoir.ch/billeterie/"
      date: "2025-04-12"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Nouveau_Monde_2024.webp"
      web_url: "https://www.nouveaumonde.ch/agenda/"
      date: "2024-11-16"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Globull_2024.webp"
      web_url: "https://tickets.globull.ch/shop/fr"
      date: "2024-11-01"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Francomanias_2024.webp"
      web_url: "https://www.francomanias.ch/programmation"
      date: "2024-08-31"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/Festival_de_la_Cabane_2024.webp"
      web_url: "https://festivaldelacabane.ch/"
      date: "2024-08-10"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952384/Synyster%20Website/posters/Abyss_Festival_2024.webp"
      web_url: "https://www.abyssfestival.ch/#billeterie"
      date: "2024-06-27"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/The_Rockies_2024.webp"
      web_url: "https://www.instagram.com/rockieslausanne/"
      date: "2024-06-08"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205126/Synyster%20Website/posters/Union_2024.webp"
      web_url: "https://www.lunion-bulle.ch/"
      date: "2024-03-02"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Monsters_Of_Bulle_2024.webp"
      web_url: "https://youtu.be/iQOOQ7KFmdE"
      date: "2024-02-03"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205128/Synyster%20Website/posters/Bad_Bonn_2023.webp"
      web_url: "https://club.badbonn.ch/archive/2023/mesmerised-upload-synister"
      date: "2023-11-11"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Qwertz_2023.webp"
      web_url: "https://qwertz.gg/"
      date: "2023-10-07"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/III%C3%A8me_2023.webp"
      web_url: "https://www.instagram.com/bar_le_3e_bulle/"
      date: "2023-09-28"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/Francomanias_2023.webp"
      web_url: "https://www.francomanias.ch/programmation"
      date: "2023-09-02"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/Lapin_Vert_2023.webp"
      web_url: "https://www.instagram.com/lapinvertlausanne/"
      date: "2023-09-01"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/Park_St-Paul_2023.webp"
      web_url: ""
      date: "2023-08-26"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/RJG_2023.webp"
      web_url: "https://www.jeunesse-gruyeres.ch/"
      date: "2023-07-02"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205128/Synyster%20Website/posters/Cabal%27%C3%89t%C3%A9_2023.webp"
      web_url: "https://www.bulle.ch/actualitescommunales/2166016"
      date: "2023-06-30"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732205127/Synyster%20Website/posters/FM_Bulle_2023.webp"
      web_url: "https://fmbulle.ch/"
      date: "2023-06-17"
  videos:
    - web_url: "https://www.youtube.com/embed/iQOOQ7KFmdE?si=MztkAcw3KF377-3T"
    - web_url: "https://www.youtube.com/embed/IOUMo9eb5gw?si=nfyRtDWbEBnBclSi"
  pictures:
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952380/Synyster%20Website/pictures/Globull-2024-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228671/Synyster%20Website/pictures/Monsters_of_Bulle-2024-7.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952381/Synyster%20Website/pictures/Monsters_of_Bulle-2024-1.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952379/Synyster%20Website/pictures/Festival_de_la_Cabane-2024-1.webp"
      caption: "Camille Paccaud"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952380/Synyster%20Website/pictures/Francomanias-2023-1.webp"
      caption: "Théo Hanselmann"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228669/Synyster%20Website/pictures/Globull-2024-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228669/Synyster%20Website/pictures/Ruined-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952381/Synyster%20Website/pictures/Monsters_of_Bulle-2024-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/First_shooting-2.webp"
      caption: "Pedro Pombeiro"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1735904688/Synyster%20Website/pictures/Francomanias-2023-2.jpg"
      caption: "Théo Hanselmann"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228671/Synyster%20Website/pictures/Monsters_of_Bulle-2024-4.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228672/Synyster%20Website/pictures/Monsters_of_Bulle-2024-8.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228672/Synyster%20Website/pictures/Monsters_of_Bulle-2024-9.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228671/Synyster%20Website/pictures/Monsters_of_Bulle-2024-6.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228669/Synyster%20Website/pictures/Globull-2024-3.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228669/Synyster%20Website/pictures/Globull-2024-4.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228670/Synyster%20Website/pictures/Globull-2024-5.webp"
      caption: "Lilou Boschung"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952380/Synyster%20Website/pictures/Monsters_of_Bulle-2024-3.webp"
      caption: "Joseph Carlucci"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Abyss_Festival-2024-1.webp"
      caption: "Photophobie"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732230443/Synyster%20Website/pictures/Festival_de_la_Cabane-2024-2.webp"
      caption: "Camille Paccaud"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228669/Synyster%20Website/pictures/Bad_Bonn-2023-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228671/Synyster%20Website/pictures/Bad_Bonn-2023-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732228671/Synyster%20Website/pictures/Bad_Bonn-2023-3.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/First_shooting-1.webp"
      caption: "Pedro Pombeiro"
  home:
    logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732184156/Synyster%20Website/home/logo.webp"
    background: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732184156/Synyster%20Website/home/background.webp"
  about:
    logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1732184240/Synyster%20Website/about/logo.webp"
    background: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/background.webp"
    band: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952357/Synyster%20Website/about/band.webp"
    band_members:
      - name: "Diogo Pombeiro"
        web_url: "https://www.instagram.com/necrom_dp"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Diogo.webp"
        role: "guitar"
      - name: "Antoine Borcard"
        web_url: "https://www.instagram.com/antbor.s"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Antoine.webp"
        role: "bass"
      - name: "Samuel Bielmann"
        web_url: "https://www.instagram.com/sam_blmn"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Samuel.webp"
        role: "vocals"
      - name: "Simone Dal Molin"
        web_url: "https://www.instagram.com/simd.al08"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Simone.webp"
        role: "drums"
      - name: "Rémi Castella"
        web_url: "https://www.instagram.com/remi.castella"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Rémi.webp"
        role: "guitar"
