media:
  templates:
    footer_logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/templates/footer-logo.webp"
  posters:
    upcoming_shows:
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952385/Synyster%20Website/posters/Glubull.webp"
        web_url: "https://www.instagram.com/necrom_dp"
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Nouveau_Monde.webp"
        web_url: "https://www.instagram.com/remi.castella"
    past_shows:
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Francos.webp"
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Rockies.webp"
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Qwertz.webp"
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/Abyss.webp"
      - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952386/Synyster%20Website/posters/MoB.webp"
  videos:
    - web_url: "https://www.youtube.com/embed/iQOOQ7KFmdE?si=MztkAcw3KF377-3T"
    - web_url: "https://www.youtube.com/embed/IOUMo9eb5gw?si=nfyRtDWbEBnBclSi"
  pictures:
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Abyss-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Abyss-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Globull-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Bad_Bonn-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Cabane-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Cabane-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/First_shooting-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/First_shooting-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/Francos_2023-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/MoB-1.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/MoB-2.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952378/Synyster%20Website/pictures/MoB-3.webp"
    - image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/pictures/Ruined-1.webp"
  home:
    logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952368/Synyster%20Website/home/logo.webp"
    background: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952368/Synyster%20Website/home/background.webp"
  about:
    logo: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/logo.webp"
    background: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/background.webp"
    band: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952357/Synyster%20Website/about/band.webp"
    band_members:
      - name: "Diogo Pombeiro"
        web_url: "https://www.instagram.com/necrom_dp"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Diogo.webp"
        role: "guitar"
      - name: "Antoine Borcard"
        web_url: "https://www.instagram.com/antbor.s"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Antoine.webp"
        role: "bass"
      - name: "Samuel Bielmann"
        web_url: "https://www.instagram.com/sam_blmn"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Samuel.webp"
        role: "vocals"
      - name: "Simone Dal Molin"
        web_url: "https://www.instagram.com/simd.al08"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Simone.webp"
        role: "drums"
      - name: "Rémi Castella"
        web_url: "https://www.instagram.com/remi.castella"
        image_path: "https://res.cloudinary.com/dlgrvwzkz/image/upload/v1731952358/Synyster%20Website/about/Rémi.webp"
        role: "guitar"
